//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YETI
{
    using System;
    using System.Collections.Generic;
    
    public partial class cqc_exports
    {
        public int ci_id { get; set; }
        public string cs_nombre { get; set; }
        public string cs_address { get; set; }
        public string cs_locacion { get; set; }
        public string cs_phone { get; set; }
        public string cs_ein { get; set; }
    }
}
