//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YETI
{
    using System;
    using System.Collections.Generic;
    
    public partial class cqc_usuarios
    {
        public int ci_id { get; set; }
        public string cs_nombre { get; set; }
        public string cs_correo { get; set; }
        public string cs_contrasena { get; set; }
        public DateTime cs_alta { get; set; }
        public DateTime cs_modificacion { get; set; }
        public bool cb_active { get; set; }
        public bool cb_southBound { get; set; }
        public bool cb_northBount { get; set; }
        public bool cb_masters { get; set; }
        public bool cb_workOrder { get; set; }
        public bool cb_ups { get; set; }
        public bool cb_scrap { get; set; }
        public bool cb_balance { get; set; }
    }
}
