//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YETI
{
    using System;
    using System.Collections.Generic;
    
    public partial class cqc_skus
    {
        public int ci_id { get; set; }
        public string cs_sku { get; set; }
        public string cs_plant { get; set; }
        public string cs_description { get; set; }
        public string cs_comodityCode { get; set; }
        public Nullable<decimal> cs_cost { get; set; }
        public string cs_materialGroup { get; set; }
    }
}
