//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YETI
{
    using System;
    using System.Collections.Generic;
    
    public partial class cqf_workOrder
    {
        public int fi_id { get; set; }
        public string fc_status { get; set; }
        public string fs_workOrder { get; set; }
        public System.DateTime fdt_date { get; set; }
        public string fs_sku { get; set; }
        public string fs_paintCode { get; set; }
        public string fs_engraving { get; set; }
        public int fi_qty { get; set; }
    }
}
