//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YETI
{
    using System;
    using System.Collections.Generic;
    
    public partial class cqf_WorkOrderMaster
    {
        public int fi_id { get; set; }
        public string fc_status { get; set; }
        public string fs_workOrder { get; set; }
        public System.DateTime fdt_date { get; set; }
        public string fs_shipperUpsAccount { get; set; }
        public string fs_reference { get; set; }
        public string fs_name { get; set; }
        public string fs_telephone { get; set; }
        public string fs_company { get; set; }
        public string fs_streetAddress { get; set; }
        public string fs_cityState { get; set; }
        public string fs_deliverToName { get; set; }
        public string fs_deliverPhone { get; set; }
        public string fs_deliverCompany { get; set; }
        public string fs_deliverStreetAddress { get; set; }
        public string fs_deliverCityState { get; set; }
        public double fd_weightLbs { get; set; }
        public double fd_dimentionalWeight { get; set; }
        public double fd_largePackage { get; set; }
        public string fs_shipperRelease { get; set; }
        public decimal fd_groundSdpShippingCharges { get; set; }
        public decimal fd_declareValueCarriage { get; set; }
        public decimal fd_amount { get; set; }
        public decimal fd_aditionalHandlingCharge { get; set; }
        public decimal fd_totalCharges { get; set; }
        public bool fb_billShipperAccountNumber { get; set; }
        public bool fb_billReceiver { get; set; }
        public bool fb_billThirdParty { get; set; }
        public bool fb_billCreditCard { get; set; }
        public string fs_receiversThirdPartyUpsAcct { get; set; }
        public string fs_thirdPartCompanyName { get; set; }
        public string fs_thirdStreetAddress { get; set; }
        public string fs_thirdCityState { get; set; }
    }
}
