//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YETI
{
    using System;
    using System.Collections.Generic;
    
    public partial class cqf_immexTransfer
    {
        public int fi_id { get; set; }
        public System.DateTime fdt_fecha { get; set; }
        public string fs_immexNombre { get; set; }
        public string fs_sku { get; set; }
        public Nullable<int> fi_qty { get; set; }
        public string fs_file { get; set; }
    }
}
