//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YETI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterInvoiceSB
    {
        public string fc_status { get; set; }
        public string fs_invoice { get; set; }
        public string fs_trucker { get; set; }
        public string fs_tracking { get; set; }
        public Nullable<System.DateTime> fd_date { get; set; }
        public string fs_productionOrder { get; set; }
        public string fs_reference { get; set; }
        public string fs_moneda { get; set; }
        public Nullable<double> fd_totalWeightKgs { get; set; }
        public Nullable<double> fs_totalWightLbs { get; set; }
        public Nullable<decimal> fd_exitPrice { get; set; }
    }
}
