//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YETI
{
    using System;
    using System.Collections.Generic;
    
    public partial class NorthBound
    {
        public int fi_id { get; set; }
        public string fc_status { get; set; }
        public Nullable<System.DateTime> fdt_invoiceDate { get; set; }
        public string fs_invoiceNumber { get; set; }
        public string fs_trailerNumber { get; set; }
        public string fs_sealNumber { get; set; }
        public Nullable<int> fi_exportOfRecord { get; set; }
        public string fs_exportOfRecord { get; set; }
        public Nullable<int> fi_importer { get; set; }
        public string fs_importer { get; set; }
        public Nullable<int> fi_shipper { get; set; }
        public string fs_shipper { get; set; }
        public Nullable<int> fi_shipTo { get; set; }
        public string fs_shipTo { get; set; }
        public string fs_incoterm { get; set; }
        public Nullable<System.DateTime> fdt_shipDate { get; set; }
        public string fs_shipVia { get; set; }
        public string fs_SKU { get; set; }
        public string fs_descYeti { get; set; }
        public string fs_hsCodeYeti { get; set; }
        public string fs_COOYeti { get; set; }
        public Nullable<int> fi_qtyYeti { get; set; }
        public Nullable<decimal> fd_unitPriceYeti { get; set; }
        public Nullable<decimal> fd_extPriceYeti { get; set; }
        public string fs_descSP { get; set; }
        public string fs_hsCodeSP { get; set; }
        public string fs_COOSP { get; set; }
        public Nullable<decimal> fd_unitPriceSP { get; set; }
        public Nullable<decimal> fd_extPriceSP { get; set; }
        public string fs_WONumber { get; set; }
        public string fs_upsTracking { get; set; }
        public Nullable<decimal> fd_totalEnteredValue { get; set; }
        public Nullable<double> fd_totalWeight { get; set; }
        public Nullable<decimal> fd_totalAmount { get; set; }
    }
}
