//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YETI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SouthBound
    {
        public int fi_id { get; set; }
        public string fc_status { get; set; }
        public string fs_invoice { get; set; }
        public string fs_trucker { get; set; }
        public string fs_tracking { get; set; }
        public Nullable<System.DateTime> fd_date { get; set; }
        public string fs_productionOrder { get; set; }
        public string fs_reference { get; set; }
        public string fs_incoterms { get; set; }
        public Nullable<System.DateTime> fd_shipDate { get; set; }
        public Nullable<int> fi_exportRecords { get; set; }
        public string fs_exportRecords { get; set; }
        public Nullable<int> fi_importRecords { get; set; }
        public string fs_importRecords { get; set; }
        public Nullable<int> fi_shipper { get; set; }
        public string fs_shipper { get; set; }
        public Nullable<int> fi_shipTo { get; set; }
        public string fs_shipTo { get; set; }
        public string fs_partNumber { get; set; }
        public string fs_description { get; set; }
        public string fs_scheduleHsCode { get; set; }
        public string fs_coo { get; set; }
        public Nullable<int> fi_qty { get; set; }
        public Nullable<double> fd_totalWeightLbs { get; set; }
        public Nullable<decimal> fd_unitPrice { get; set; }
        public Nullable<double> fd_totalWeightKgs { get; set; }
        public Nullable<decimal> fd_exitPrice { get; set; }
        public string fs_moneda { get; set; }
    }
}
